FROM python
RUN pip install Flask Flask-SQLAlchemy
RUN mkdir /app
#Copy sources to app directory
COPY . /app
EXPOSE 5000
ENV FLASK_APP srik_test.py
#WORKDIR /app
CMD flask run & > app.log
#CMD ["/bin/sh"]

