# Default Elasticsearch configuration.
cluster.name: "docker-cluster"
network.host: 0.0.0.0
# minimum_master_nodes, set to 1 to allow single node clusters
# Details: https://github.com/elastic/elasticsearch/pull/17288
discovery.zen.minimum_master_nodes: 1
# Use single node discovery in order to disable production mode and # avoid bootstrap checks
discovery.type: single-node
